apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: combo-preview
resources:
  - ../../../job-migrate.yaml
patches:
  - path: migrate.patch.yaml
images:
  - name: ghcr.io/dangdang-tech/combo-api
    newTag: cloud-review
labels:
  - pairs:
      app.kubernetes.io/part-of: combo-cloud-review
      combo.build/environment: cloud-review
    includeSelectors: false
