apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: combo-review
resources:
  - namespace.yaml
  - ../../../postgres.yaml
  - ../../../redis-queue.yaml
  - ../../../redis-hot.yaml
  - ../../../minio.yaml
  - ../../../job-minio-init.yaml
patches:
  - path: postgres.patch.yaml
  - path: redis-queue.patch.yaml
  - path: redis-hot.patch.yaml
  - path: minio.patch.yaml
  - path: minio-init.patch.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: combo-cloud-review
      combo.build/environment: cloud-review
    includeSelectors: false
