apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: combo-foundation
resources:
  - ../../postgres.yaml
  - ../../redis-hot.yaml
  - ../../minio.yaml
  - ../../job-minio-init.yaml
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      combo.build/foundation-set: shared
